### ISSUE TITLE
The install location of the book is not suitable for opening by all browsers

### ISSUE THREAD

**Issue by amodm** [0xhiro/thebook#7]
Some browsers block access to filesystem urls where a path component starts with dot (.)

This emerged during [my testing described here](https://github.com/amodm/webbrowser-rs/issues/55#issuecomment-1365149214). Because the book is installed under `~/.thebook`, Firefox & Chrome (on Ubuntu 22.04 at least) do not open the book (see screenshot).

The moment I changed the location to `~/thebook` instead of `~/.thebook`, it worked.

![image](https://user-images.githubusercontent.com/1546858/209552441-ea7c9e19-8191-46e7-92ab-fa6c05d19697.png)

**Comment by 0xhiro** [comment]
Oh! That's interesting. Thanks for the find. Removing the dot won't hurt. I'll include that in the next merge. Thanks again :)

**Comment by 0xhiro** [comment]
This issue has been fixed in the latest version. Please do `cargo install thebook` to try it out. Thanks!

**Comment by 0xhiro** [comment]
It turns out this is also an issue in the rustup method of opening the book `rustup doc --book`. this happens because the browser, mostly `firefox` was probably installed using `snap`. Though i have changed the install location from `.thebook` to `thebook`, rustup still suffers from this issue because it is installed in `.rustup`

**Comment by amodm** [comment]
The release should be out by this weekend, hopefully sooner. I'll ping here when that happens. And good point about the `rustup` thing. Once the release is out, I'll raise a ticket there too.
